apiVersion: v1
kind: PersistentVolume

metadata:
  name: red-pv-ckad03-str

spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /yourmom/red-pv-ckad03-str
  claimRef:
    name: red-pv-ckad03-str