apiVersion: batch/v1
kind: Job
metadata:
  namespace: ckad-job
  name: my-simple-job
spec:
  template:
    spec:
      containers:
        - name: my-simple-job
          image: busybox
          command:
            - /bin/sh
            - -c
            - ps -eaf
      restartPolicy: OnFailure
