apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: ckad-pod-design
spec:
  containers:
  - name: some-container
    image: nginx:1.17
  securityContext:
    privileged: true


# Set pod to privileged
