apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2023-09-24T05:22:48Z"
    name: pod-creater
    namespace: ckad20-auth-aecs
    resourceVersion: "15420"
    uid: 1ff9699a-a655-401e-88b4-a9a5069e600e
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - create
    - list
kind: List
