apiVersion: v1
kind: Pod
metadata:
  name: healthy-server
  namespace: ckad-multi-containers
  labels:
    app.kubernetes.io/name: health-server
spec:
  containers:
  - name: main
    image: busybox:1.28
    command:
      - sh
      - -c
      - echo The app is running! && sleep 3600

  - name: init
    image: busybox:1.28
    command:
      - sh
      - -c
      - echo Initialize application environment! && sleep 10
