apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app-xnz":"route02","tier-ii":"square-apd"},"name":"square-apd","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app-xnz":"route02"}},"template":{"metadata":{"labels":{"app-xnz":"route02"}},"spec":{"containers":[{"image":"kodekloud/webapp-color:v2","name":"square-apd"}]}}}}
  creationTimestamp: "2023-07-25T10:07:51Z"
  generation: 1
  labels:
    app-xnz: route02
    tier-ii: square-apd
  name: square-apd
  namespace: default
  resourceVersion: "10029"
  uid: 705a9686-1cf3-4d26-ac76-f7b2942a348e
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app-xnz: route02
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app-xnz: route02
    spec:
      containers:
      - image: kodekloud/webapp-color:v2
        imagePullPolicy: IfNotPresent
        name: square-apd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-07-25T10:08:00Z"
    lastUpdateTime: "2023-07-25T10:08:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-07-25T10:07:51Z"
    lastUpdateTime: "2023-07-25T10:08:00Z"
    message: ReplicaSet "square-apd-64dd596fdb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3