apiVersion: v1
kind: Service

metadata:
  name: route-apd-svc
  labels:
    app: route-apd-svc

spec:
  type: NodePort

  selector:
    version: v1

  ports:
    - protocol: TCP 
      targetPort: 8080
      port: 8080
