apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc-ckad02-str

spec:
  storageClassName: manual
  volumeName: data-pvc-ckad02-str
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

  
