apiVersion: v1
kind: Pod
metadata:
  name: ckad-sidecar-pod
  namespace: ckad-multi-containers

spec:
  containers:

    - name: main-container
      image: busybox:1.28
      volumeMounts:
        - name: my-vol
          mountPath: /usr/share/nginx/html

    - name: sidecar-conatiner
      image:  busybox:1.28
      command:
        - /bin/sh
        - -c
        - while true; do echo $(date -u) Hi I am from Sidecar container >> /var/log/index.html; sleep 5;done
      volumeMounts:
        - name: my-vol
          mountPath: /var/log

  volumes:
    - name: my-vol
      emptyDir: {}

# Done is important
