# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   namespace: nginx-depl-svcn
#   name: nginx-ckad10-svcn

# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nginx-ckad

#   template:
#     metadata:
#       labels:
#         app: nginx-ckad

#     spec:
#       containers:
#         - name: nginx
#           image: nginx
#           ports:
#             - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: nginx-ckad10-service-svcn
spec:
  selector:
    app: nginx-ckad
  port:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIp



# apiVersion: v1
# kind: Pod
# metadata:
#   name: pod21-ckad-svcn
#   labels:
#     v: v1

# spec:
#   containers:
#     - name: pod21-ckad-svcn
#       image: nginx:alpine
    

# apiVersion: v1
# kind: Service
# metadata:
#   name: ckad15-service-svcn
# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     v: v1
#   name: ckad15-depl-svc
# spec:
#   ports:
#   - port: 30085
#     protocol: TCP
#     targetPort: 8080
#     nodePort: 30085
#   selector:
#     v: v1
#   type: NodePort
# status:
#   loadBalancer: {}
  

# apiVersion: apps/v1
# kind: Deployment

# metadata:
#   name: ckad15-depl-svc
#   labels:
#     v: v1

# spec:
#   replicas: 2

#   selector:
#     matchLabels:
#       v: v1

#   template:
#     metadata:
#       labels:
#         v: v1

#     spec:
#       containers:
#         - name: ckad15-depl-svcn
#           image: nginx
#           ports:
#             - containerPort: 80