apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ckad23-nssa-aecs
  name: wide-access-rb-aecs
subjects:
  - kind: ServiceAccount
    name: ckad23-sa-aecs
    namespace: ckad23-nssa-aecs
roleRef:
  kind: Role
  name: wide-access-aecs
  apiGroups: rbac.authorization.k8s.io

